version: "3.8"
services:
  postgres:
    image: postgres
    restart: on-failure:10
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    restart: on-failure:10
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./internal/db/postgres/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]
  api:
    restart: on-failure:10
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - migrate
    volumes:
      - ${SERVICE_ACCOUNT_FILE}:/tmp/keys/serviceAccountKey.json:ro
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
volumes:
  pg_data: